name: AzCopy Ubuntu Agent Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  STORAGE_ACCOUNT: storterraformd01
  CONTAINER: azcopycontainer
  STAGE_NAME: AzCopy_Ubuntu_Agent_Test
  AGENT_IMAGE: ubuntu-latest
  AZCOPY_LOG_PATH: /home/runner/.azcopy
  SAS_TOKEN: ${{ secrets.SAS_TOKEN }} # Use GitHub Secrets for security

jobs:
  azcopy_ubuntu_agent_test:
    name: ${{ env.STAGE_NAME }}
    runs-on: ${{ env.AGENT_IMAGE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Print AzCopy Environment
        shell: pwsh
        run: azcopy env

      - name: Run AzCopy PowerShell Script
        shell: pwsh
        continue-on-error: true
        run: |
          ./AzCopy-Wrapper.ps1 `
            -SourceFolder "${{ github.workspace }}/test-images" `
            -StorageAccount "${{ env.STORAGE_ACCOUNT }}" `
            -StorageContainer "${{ env.CONTAINER }}" `
            -SasToken "${{ env.SAS_TOKEN }}" `
            -TargetFolderPrefix "from-github-actions"

      - name: Print AzCopy Logs
        shell: pwsh
        run: |
          $LogPath = "${{ env.AZCOPY_LOG_PATH }}"
          $LogFiles = Get-ChildItem -Path $LogPath -Filter "*.log"
          foreach ($file in $LogFiles) {
              Write-Host "`n--- Contents of: $($file.FullName) ---`n"
              Get-Content $file.FullName
          }
