name: AzCopy Ubuntu Agent

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  workflow_dispatch:

env:
  storageAccount: storterraformd01
  container: azcopycontainer

jobs:
  gha-ubuntu-azcopy:
    name: AzCopy Ubuntu Agent
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Az Copy Test
        continue-on-error: true
        shell: pwsh
        run: |
          azcopy copy "./seed_images/*" "https://${{ env.storageAccount }}.blob.core.windows.net/${{ env.container }}/gha-ubuntu?$SAS_TOKEN" --recursive=true
        env:
          SAS_TOKEN: ${{ secrets.SAS_TOKEN }}

      - name: Print log
        working-directory: /home/runner/.azcopy
        run: |
          cat *.log
