trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '*'

#trigger: none

variables:
  - group: sas-token-group
  - name: 'storageAccount'
    value: 'storterraformd01'
  - name: 'container'
    value: 'azcopycontainer'

stages:
  - stage: 'AzCopy_Ubuntu_Agent'
    displayName: 'AzCopy Ubuntu Agent'
    jobs:
      - job: 'Build'
        displayName: 'AzCopy Ubuntu Agent'
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - checkout: self
            fetchDepth: 0

          - script: |
              azcopy env
            displayName: 'Print AzCopy ENV'
            workingDirectory: /home/vsts/.azcopy/

          - script: |
              azcopy copy "./test-images/*" "https://$(storageAccount).blob.core.windows.net/$(container)/ubuntu?$(sas-token)" --recursive=true
            displayName: 'AzCopy Ubuntu Agent'
            continueOnError: true

          - script: |
              cat *log
            displayName: 'Print log output'
            workingDirectory: /home/vsts/.azcopy/

          - task: AzureCLI@2
            displayName: 'AzCopy via Azure CLI'
            inputs:
              azureSubscription: 'AzureServiceConnection'
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: |
                azcopy copy "./test-images/*" "https://$(storageAccount).blob.core.windows.net/$(container)/ubuntu-az-cli?$(sas-token)" --recursive=true
