trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '*'

#trigger: none

variables:
  - group: SAS_GROUP
  - name: 'rgName'
    value: 'rg-tf-state102-uat02'
  - name: 'storageAccount'
    value: 'sttfstate259'
  - name: 'container'
    value: 'azcopyazpipelineubuntu'

stages:
  - stage: 'AzCopy_Ubuntu_Agent'
    displayName: 'AzCopy Ubuntu Agent'
    jobs:
      - job: 'Build'
        displayName: 'AzCopy Ubuntu Agent'
        pool:
          vmImage: 'ubuntu-latest'
        
        steps:
          - checkout: self
            fetchDepth: 0

          - script: |
              azcopy copy "./seed_images/*" "https://$(storageAccount).blob.core.windows.net/$(container)?$(SAS)" --recursive=true
            displayName: 'AzCopy Ubuntu Agent'

          - task: AzureCLI@2
            displayName: 'AzCopy via Azure CLI'
            inputs:
              azureSubscription: 'AzCopyARM'
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: |
                $Date = (Get-Date).AddDays(1).ToString('yyyy-MM-dd')
                $key = $( az storage account keys list --resource-group $(rgName) --account-name $(storageAccount) --query [0].value -o tsv )
                Write-Output "Key: $key"
                $sas = $( az storage container generate-sas --name $(container) --expiry $Date --permissions "racwdli" --account-name $(storageAccount) --account-key "$key" )
                Write-Output "SAS: $sas"
                azcopy copy "./seed_images/*" "https://$(storageAccount).blob.core.windows.net/$(container)/from_az_cli?$(SAS)" --recursive=true